### ISSUE TITLE
Call trace RIP: 0010:wiphy_register+0x68a/0x940 [cfg80211]

### ISSUE THREAD

**Issue by luckylittle** [brektrou/rtl8821CU#107]
* Red Hat Enterprise Linux release `8.3` (Ootpa)
* Kernel `4.18.0-240.1.1.el8_3.x86_64`
* Device: `EDUP EP-AC1661 2-in-1 WiFi+BT`
* Driver: rtl8821cu v`5.8.1_34171.20190628_COEX20190509-4141` with [this little change](https://github.com/brektrou/rtl8821CU/issues/30#issuecomment-743923510)
* Compiles with no reported errors

1. 
```bash
sudo modprobe 8821cu # complains about missing `rtw_RFE_type`
```

```text
[ 9457.043130] RTW: module init start
[ 9457.043132] RTW: rtl8821cu v5.8.1_34171.20190628_COEX20190509-4141
[ 9457.043132] RTW: build time: Dec 12 2020 23:15:59
[ 9457.043133] RTW: rtl8821cu BT-Coex version = COEX20190509-4141
[ 9457.043282] RTW: [HALMAC]11692M
               HALMAC_MAJOR_VER = 1
               HALMAC_PROTOTYPE_VER = 6
               HALMAC_MINOR_VER = 5
               HALMAC_PATCH_VER = 5
[ 9457.043751] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[ 9457.126749] RTW: HW EFUSE
[ 9457.126751] RTW: 0x000: 29 81 00 BC  09 00 21 00  6E 04 A4 34  10 00 30 0B  
[ 9457.126754] RTW: 0x010: 1C 1D 1E 20  20 20 24 25  26 28 28 FF  FF FF FF FF  
[ 9457.126757] RTW: 0x020: FF FF 26 28  28 28 2A 2A  2A 2A 2A 2A  25 26 26 26  
[ 9457.126760] RTW: 0x030: 00 FF FF FF  FF FF FF FF  FF FF 1C 1D  1E 20 20 20  
[ 9457.126762] RTW: 0x040: 24 25 26 28  28 02 FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126765] RTW: 0x050: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126768] RTW: 0x060: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126770] RTW: 0x070: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126773] RTW: 0x080: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126775] RTW: 0x090: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126778] RTW: 0x0A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126781] RTW: 0x0B0: FF FF FF FF  FF FF FF FF  7F 0A 1F 00  FF FF FF FF  
[ 9457.126783] RTW: 0x0C0: FF 21 00 00  00 00 00 00  00 26 FF FF  FF FF FF FF  
[ 9457.126786] RTW: 0x0D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126788] RTW: 0x0E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126791] RTW: 0x0F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126794] RTW: 0x100: DA 0B 20 C8  E3 46 FF E8  4E 06 88 EF  52 09 03 52  
[ 9457.126796] RTW: 0x110: 65 61 6C 74  65 6B 0E 03  38 30 32 2E  31 31 61 63  
[ 9457.126799] RTW: 0x120: 20 4E 49 43  04 03 46 46  FF FF FF FF  FF FF FF FF  
[ 9457.126802] RTW: 0x130: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126804] RTW: 0x140: FF FF FF FF  00 00 31 0F  FF FF FF FF  FF FF FF FF  
[ 9457.126807] RTW: 0x150: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126809] RTW: 0x160: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126812] RTW: 0x170: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126815] RTW: 0x180: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126817] RTW: 0x190: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126820] RTW: 0x1A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126822] RTW: 0x1B0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126825] RTW: 0x1C0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126828] RTW: 0x1D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126830] RTW: 0x1E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126833] RTW: 0x1F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 9457.126906] RTW: hal_com_config_channel_plan chplan:0x7F
[ 9457.126906] RTW: ERROR 
               Empty EFUSE with unknown REF type!!
[ 9457.126907] RTW: ERROR please program efuse or specify correct RFE type.
[ 9457.126907] RTW: ERROR cmd: insmod rtl8821cx.ko rtw_RFE_type=<rfe_type>
[ 9457.126954] usbcore: registered new interface driver rtl8821cu
[ 9457.126955] RTW: module init ret=0
```

2. As suggested in #83 , value of rtw_RFE_type was provided
```bash
sudo modprobe -r 8821cu
sudo modprobe 8821cu rtw_RFE_type=7 # produces call trace
```

```text
[14701.349388] RTW: module init start
[14701.349390] RTW: rtl8821cu v5.8.1_34171.20190628_COEX20190509-4141
[14701.349391] RTW: build time: Dec 12 2020 23:15:59
[14701.349391] RTW: rtl8821cu BT-Coex version = COEX20190509-4141
[14701.349564] RTW: [HALMAC]11692M
               HALMAC_MAJOR_VER = 1
               HALMAC_PROTOTYPE_VER = 6
               HALMAC_MINOR_VER = 5
               HALMAC_PATCH_VER = 5
[14701.350044] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[14701.433023] RTW: HW EFUSE
[14701.433025] RTW: 0x000: 29 81 00 BC  09 00 21 00  6E 04 A4 34  10 00 30 0B  
[14701.433029] RTW: 0x010: 1C 1D 1E 20  20 20 24 25  26 28 28 FF  FF FF FF FF  
[14701.433032] RTW: 0x020: FF FF 26 28  28 28 2A 2A  2A 2A 2A 2A  25 26 26 26  
[14701.433034] RTW: 0x030: 00 FF FF FF  FF FF FF FF  FF FF 1C 1D  1E 20 20 20  
[14701.433037] RTW: 0x040: 24 25 26 28  28 02 FF FF  FF FF FF FF  FF FF FF FF  
[14701.433039] RTW: 0x050: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433042] RTW: 0x060: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433045] RTW: 0x070: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433047] RTW: 0x080: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433050] RTW: 0x090: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433052] RTW: 0x0A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433055] RTW: 0x0B0: FF FF FF FF  FF FF FF FF  7F 0A 1F 00  FF FF FF FF  
[14701.433058] RTW: 0x0C0: FF 21 00 00  00 00 00 00  00 26 FF FF  FF FF FF FF  
[14701.433060] RTW: 0x0D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433063] RTW: 0x0E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433066] RTW: 0x0F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433068] RTW: 0x100: DA 0B 20 C8  E3 46 FF E8  4E 06 88 EF  52 09 03 52  
[14701.433071] RTW: 0x110: 65 61 6C 74  65 6B 0E 03  38 30 32 2E  31 31 61 63  
[14701.433073] RTW: 0x120: 20 4E 49 43  04 03 46 46  FF FF FF FF  FF FF FF FF  
[14701.433076] RTW: 0x130: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433079] RTW: 0x140: FF FF FF FF  00 00 31 0F  FF FF FF FF  FF FF FF FF  
[14701.433081] RTW: 0x150: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433084] RTW: 0x160: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433087] RTW: 0x170: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433089] RTW: 0x180: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433092] RTW: 0x190: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433094] RTW: 0x1A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433097] RTW: 0x1B0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433100] RTW: 0x1C0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433102] RTW: 0x1D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433105] RTW: 0x1E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433107] RTW: 0x1F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[14701.433179] RTW: hal_com_config_channel_plan chplan:0x7F
[14701.438358] RTW: [HALMAC][ALWAYS]shall R reg twice!!
[14701.487369] RTW: WARN [HALMAC][WARN]the H2C ver. does not match halmac
[14701.491371] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[14701.491444] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[14701.491558] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[14701.491632] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[14701.491711] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[14701.491787] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[14701.491874] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[14701.491970] RTW: [RF_PATH] IC's RF PATH:RF_1T1R, max_tx_cnt:1
[14701.491971] RTW: [RF_PATH] PG's trx_path_bmp:0x00, max_tx_cnt:0
[14701.491972] RTW: [RF_PATH] Registry's RF PATH:UNKNOWN
[14701.491973] RTW: [RF_PATH] HALDATA's trx_path_bmp:0x11, max_tx_cnt:1
[14701.491973] RTW: [RF_PATH] HALDATA's RF PATH:RF_1T1R
[14701.491974] RTW: [RF_PATH] NumTotalRFPath:1
[14701.491975] RTW: [TRX_Nss] HALSPEC - tx_nss :1, rx_nss:1
[14701.491976] RTW: [TRX_Nss] Registry - tx_nss :0, rx_nss:0
[14701.491977] RTW: [TRX_Nss] HALDATA - tx_nss :1, rx_nss:1
[14701.492622] RTW: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
[14701.492751] WARNING: CPU: 3 PID: 56916 at net/wireless/core.c:867 wiphy_register+0x68a/0x940 [cfg80211]
[14701.492752] Modules linked in: 8821cu(OE+) cfg80211 hidp uinput rfcomm xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nf_nat_tftp nft_objref nf_conntrack_tftp nft_counter tun bridge stp llc nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nf_tables_set nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip6_tables nft_compat ip_set nf_tables nfnetlink cmac bnep sunrpc vfat fat intel_rapl_msr intel_rapl_common x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi irqbypass snd_hda_intel snd_intel_dspcfg btusb snd_hda_codec btrtl btbcm crct10dif_pclmul btintel crc32_pclmul snd_hda_core bluetooth snd_hwdep iTCO_wdt snd_seq mei_wdt iTCO_vendor_support wmi_bmof snd_seq_device ghash_clmulni_intel intel_cstate snd_pcm intel_uncore intel_rapl_perf ecdh_generic snd_timer rfkill i2c_i801 pcspkr lpc_ich snd mei_me mei soundcore wmi ip_tables
[14701.492799]  xfs libcrc32c sd_mod sg i915 cec ahci intel_gtt i2c_algo_bit libahci drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops libata drm e1000e crc32c_intel video dm_mirror dm_region_hash dm_log dm_mod fuse [last unloaded: cfg80211]
[14701.492813] CPU: 3 PID: 56916 Comm: modprobe Tainted: G        W  OE    --------- -  - 4.18.0-240.1.1.el8_3.x86_64 #1
[14701.492813] Hardware name: LENOVO 10AACTO1WW/SHARKBAY, BIOS FBKTDEAUS 06/16/2020
[14701.492825] RIP: 0010:wiphy_register+0x68a/0x940 [cfg80211]
[14701.492826] Code: 78 20 00 74 25 83 ea 01 48 8d 14 52 48 c1 e2 04 48 01 c2 48 83 78 10 00 74 1c 48 39 c2 74 5a 48 83 c0 30 48 83 78 20 00 75 e9 <0f> 0b b8 ea ff ff ff e9 8a fa ff ff 48 83 78 18 00 75 dd 0f 0b b8
[14701.492827] RSP: 0018:ffff9b4f087879e0 EFLAGS: 00010246
[14701.492828] RAX: ffffffffc12b8a20 RBX: ffff8949974354a0 RCX: 0000000000000000
[14701.492829] RDX: 0000000000000002 RSI: ffff894986968858 RDI: 0000000000000001
[14701.492829] RBP: ffff9b4f08787a70 R08: 0000000000000004 R09: 0000000000000003
[14701.492830] R10: ffff89499f302000 R11: ffff89498696e800 R12: ffff9b4f02acc590
[14701.492831] R13: 0000000000000000 R14: ffff9b4f02acc4e2 R15: ffffffffc12da264
[14701.492832] FS:  00007f6f4cc23740(0000) GS:ffff894a4e8c0000(0000) knlGS:0000000000000000
[14701.492832] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[14701.492833] CR2: 000055c3b8525a70 CR3: 0000000365032003 CR4: 00000000001606e0
[14701.492834] Call Trace:
[14701.492850]  ? handle_channel_custom.isra.24.constprop.29+0x31/0x150 [cfg80211]
[14701.492922]  ? rtw_chbw_to_freq_range+0x40/0x96 [8821cu]
[14701.492957]  ? rtw_is_dfs_ch+0x34/0x70 [8821cu]
[14701.493000]  rtw_wiphy_register+0x2a/0x54 [8821cu]
[14701.493044]  rtw_cfg80211_ndev_res_register+0x15/0x56 [8821cu]
[14701.493085]  rtw_os_ndev_register+0x110/0x17b [8821cu]
[14701.493126]  rtw_os_ndevs_register+0xa7/0xf6 [8821cu]
[14701.493167]  rtw_os_ndevs_init+0x24/0x3a [8821cu]
[14701.493208]  rtw_drv_init+0x86/0xda [8821cu]
[14701.493212]  usb_probe_interface+0xe4/0x2f0
[14701.493216]  really_probe+0x212/0x440
[14701.493218]  driver_probe_device+0x49/0xc0
[14701.493219]  device_driver_attach+0x50/0x60
[14701.493221]  __driver_attach+0x61/0x130
[14701.493223]  ? device_driver_attach+0x60/0x60
[14701.493224]  bus_for_each_dev+0x77/0xc0
[14701.493228]  ? klist_add_tail+0x3b/0x70
[14701.493229]  bus_add_driver+0x14d/0x1e0
[14701.493231]  driver_register+0x6b/0xb0
[14701.493233]  usb_register_driver+0x7a/0x130
[14701.493234]  ? 0xffffffffc13fa000
[14701.493265]  rtw_drv_entry+0xc0/0x1000 [8821cu]
[14701.493270]  do_one_initcall+0x46/0x1c3
[14701.493273]  ? _cond_resched+0x15/0x30
[14701.493277]  ? kmem_cache_alloc_trace+0x140/0x1c0
[14701.493281]  do_init_module+0x5a/0x220
[14701.493283]  load_module+0x14b4/0x17e0
[14701.493286]  ? __do_sys_finit_module+0xa8/0x110
[14701.493287]  __do_sys_finit_module+0xa8/0x110
[14701.493291]  do_syscall_64+0x5b/0x1a0
[14701.493293]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[14701.493294] RIP: 0033:0x7f6f4bc0c78d
[14701.493296] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d cb 56 2c 00 f7 d8 64 89 01 48
[14701.493297] RSP: 002b:00007ffd96e30e88 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[14701.493298] RAX: ffffffffffffffda RBX: 00005566b88a8c50 RCX: 00007f6f4bc0c78d
[14701.493298] RDX: 0000000000000000 RSI: 00005566b88a9240 RDI: 0000000000000004
[14701.493299] RBP: 00005566b88a9240 R08: 0000000000000000 R09: 0000000000000000
[14701.493299] R10: 0000000000000004 R11: 0000000000000246 R12: 0000000000000000
[14701.493300] R13: 00005566b88a8b30 R14: 0000000000040000 R15: 0000000000000000
[14701.493302] ---[ end trace ab0e10acefdcbe0d ]---
[14701.493354] WARNING: CPU: 3 PID: 56916 at /home/lmaly/Downloads/WiFi/rtl8821CU-5.8.1/os_dep/linux/os_intfs.c:1903 rtw_os_ndev_register+0x64/0x17b [8821cu]
[14701.493354] Modules linked in: 8821cu(OE+) cfg80211 hidp uinput rfcomm xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nf_nat_tftp nft_objref nf_conntrack_tftp nft_counter tun bridge stp llc nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nf_tables_set nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip6_tables nft_compat ip_set nf_tables nfnetlink cmac bnep sunrpc vfat fat intel_rapl_msr intel_rapl_common x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi irqbypass snd_hda_intel snd_intel_dspcfg btusb snd_hda_codec btrtl btbcm crct10dif_pclmul btintel crc32_pclmul snd_hda_core bluetooth snd_hwdep iTCO_wdt snd_seq mei_wdt iTCO_vendor_support wmi_bmof snd_seq_device ghash_clmulni_intel intel_cstate snd_pcm intel_uncore intel_rapl_perf ecdh_generic snd_timer rfkill i2c_i801 pcspkr lpc_ich snd mei_me mei soundcore wmi ip_tables
[14701.493370]  xfs libcrc32c sd_mod sg i915 cec ahci intel_gtt i2c_algo_bit libahci drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops libata drm e1000e crc32c_intel video dm_mirror dm_region_hash dm_log dm_mod fuse [last unloaded: cfg80211]
[14701.493375] CPU: 3 PID: 56916 Comm: modprobe Tainted: G        W  OE    --------- -  - 4.18.0-240.1.1.el8_3.x86_64 #1
[14701.493376] Hardware name: LENOVO 10AACTO1WW/SHARKBAY, BIOS FBKTDEAUS 06/16/2020
[14701.493417] RIP: 0010:rtw_os_ndev_register+0x64/0x17b [8821cu]
[14701.493418] Code: 8d a7 90 35 00 00 b9 20 00 00 00 48 c7 c2 77 cf 1e c1 4c 89 e6 48 89 ef e8 f5 ec f5 d4 48 89 df e8 27 d3 01 00 83 f8 01 74 1a <0f> 0b 4c 89 e7 e8 be dc f5 d4 b8 00 00 00 00 5b 5d 41 5c 41 5d 41
[14701.493419] RSP: 0018:ffff9b4f08787aa0 EFLAGS: 00010297
[14701.493420] RAX: 0000000000000000 RBX: ffff9b4f02ac9000 RCX: 0000000000000000
[14701.493420] RDX: 0000000000000000 RSI: ffff894986968858 RDI: 0000000000000001
[14701.493421] RBP: ffff894997436000 R08: 0000000000000004 R09: 0000000000000003
[14701.493421] R10: ffff89499f302000 R11: ffff89498696e800 R12: ffff9b4f02acc590
[14701.493422] R13: 0000000000000000 R14: ffff9b4f02acc4e2 R15: ffffffffc12da264
[14701.493423] FS:  00007f6f4cc23740(0000) GS:ffff894a4e8c0000(0000) knlGS:0000000000000000
[14701.493424] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[14701.493424] CR2: 000055c3b8525a70 CR3: 0000000365032003 CR4: 00000000001606e0
[14701.493425] Call Trace:
[14701.493467]  rtw_os_ndevs_register+0xa7/0xf6 [8821cu]
[14701.493531]  rtw_os_ndevs_init+0x24/0x3a [8821cu]
[14701.493571]  rtw_drv_init+0x86/0xda [8821cu]
[14701.493573]  usb_probe_interface+0xe4/0x2f0
[14701.493575]  really_probe+0x212/0x440
[14701.493577]  driver_probe_device+0x49/0xc0
[14701.493578]  device_driver_attach+0x50/0x60
[14701.493580]  __driver_attach+0x61/0x130
[14701.493581]  ? device_driver_attach+0x60/0x60
[14701.493582]  bus_for_each_dev+0x77/0xc0
[14701.493584]  ? klist_add_tail+0x3b/0x70
[14701.493585]  bus_add_driver+0x14d/0x1e0
[14701.493587]  driver_register+0x6b/0xb0
[14701.493588]  usb_register_driver+0x7a/0x130
[14701.493589]  ? 0xffffffffc13fa000
[14701.493621]  rtw_drv_entry+0xc0/0x1000 [8821cu]
[14701.493623]  do_one_initcall+0x46/0x1c3
[14701.493625]  ? _cond_resched+0x15/0x30
[14701.493626]  ? kmem_cache_alloc_trace+0x140/0x1c0
[14701.493628]  do_init_module+0x5a/0x220
[14701.493629]  load_module+0x14b4/0x17e0
[14701.493632]  ? __do_sys_finit_module+0xa8/0x110
[14701.493633]  __do_sys_finit_module+0xa8/0x110
[14701.493635]  do_syscall_64+0x5b/0x1a0
[14701.493637]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[14701.493638] RIP: 0033:0x7f6f4bc0c78d
[14701.493639] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d cb 56 2c 00 f7 d8 64 89 01 48
[14701.493639] RSP: 002b:00007ffd96e30e88 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[14701.493640] RAX: ffffffffffffffda RBX: 00005566b88a8c50 RCX: 00007f6f4bc0c78d
[14701.493641] RDX: 0000000000000000 RSI: 00005566b88a9240 RDI: 0000000000000004
[14701.493642] RBP: 00005566b88a9240 R08: 0000000000000000 R09: 0000000000000000
[14701.493642] R10: 0000000000000004 R11: 0000000000000246 R12: 0000000000000000
[14701.493643] R13: 00005566b88a8b30 R14: 0000000000040000 R15: 0000000000000000
[14701.493644] ---[ end trace ab0e10acefdcbe0e ]---
[14701.502617] WARNING: CPU: 3 PID: 56916 at /home/lmaly/Downloads/WiFi/rtl8821CU-5.8.1/os_dep/linux/os_intfs.c:3423 rtw_os_ndevs_register+0xaf/0xf6 [8821cu]
[14701.502619] Modules linked in: 8821cu(OE+) cfg80211 hidp uinput rfcomm xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nf_nat_tftp nft_objref nf_conntrack_tftp nft_counter tun bridge stp llc nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nf_tables_set nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip6_tables nft_compat ip_set nf_tables nfnetlink cmac bnep sunrpc vfat fat intel_rapl_msr intel_rapl_common x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi irqbypass snd_hda_intel snd_intel_dspcfg btusb snd_hda_codec btrtl btbcm crct10dif_pclmul btintel crc32_pclmul snd_hda_core bluetooth snd_hwdep iTCO_wdt snd_seq mei_wdt iTCO_vendor_support wmi_bmof snd_seq_device ghash_clmulni_intel intel_cstate snd_pcm intel_uncore intel_rapl_perf ecdh_generic snd_timer rfkill i2c_i801 pcspkr lpc_ich snd mei_me mei soundcore wmi ip_tables
[14701.502647]  xfs libcrc32c sd_mod sg i915 cec ahci intel_gtt i2c_algo_bit libahci drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops libata drm e1000e crc32c_intel video dm_mirror dm_region_hash dm_log dm_mod fuse [last unloaded: cfg80211]
[14701.502658] CPU: 3 PID: 56916 Comm: modprobe Tainted: G        W  OE    --------- -  - 4.18.0-240.1.1.el8_3.x86_64 #1
[14701.502659] Hardware name: LENOVO 10AACTO1WW/SHARKBAY, BIOS FBKTDEAUS 06/16/2020
[14701.502697] RIP: 0010:rtw_os_ndevs_register+0xaf/0xf6 [8821cu]
[14701.502698] Code: 87 44 51 00 00 49 8d b5 e2 34 00 00 84 c0 74 0d 49 8d b5 f2 34 00 00 3c 01 49 0f 45 f7 e8 ab f0 ff ff 41 89 c4 83 f8 01 74 b2 <0f> 0b 85 db 75 15 48 63 db 48 8b bc dd 70 01 00 00 48 85 ff 74 05
[14701.502699] RSP: 0018:ffff9b4f08787ad8 EFLAGS: 00010297
[14701.502700] RAX: 0000000000000000 RBX: 0000000000000000 RCX: dead000000000200
[14701.502700] RDX: ffff894997436060 RSI: ffff9b4f02acc628 RDI: ffff9b4f02acc650
[14701.502701] RBP: ffff89499f302000 R08: 000000000001175f R09: 000000000001175f
[14701.502702] R10: 0000000000000000 R11: ffff894a4e8e8c64 R12: 0000000000000000
[14701.502702] R13: ffff9b4f02ac9000 R14: 0000000000000001 R15: ffffffffc12da264
[14701.502703] FS:  00007f6f4cc23740(0000) GS:ffff894a4e8c0000(0000) knlGS:0000000000000000
[14701.502704] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[14701.502704] CR2: 000055c3b8525a70 CR3: 0000000365032003 CR4: 00000000001606e0
[14701.502705] Call Trace:
[14701.502745]  rtw_os_ndevs_init+0x24/0x3a [8821cu]
[14701.502784]  rtw_drv_init+0x86/0xda [8821cu]
[14701.502788]  usb_probe_interface+0xe4/0x2f0
[14701.502792]  really_probe+0x212/0x440
[14701.502794]  driver_probe_device+0x49/0xc0
[14701.502795]  device_driver_attach+0x50/0x60
[14701.502797]  __driver_attach+0x61/0x130
[14701.502798]  ? device_driver_attach+0x60/0x60
[14701.502799]  bus_for_each_dev+0x77/0xc0
[14701.502803]  ? klist_add_tail+0x3b/0x70
[14701.502804]  bus_add_driver+0x14d/0x1e0
[14701.502806]  driver_register+0x6b/0xb0
[14701.502808]  usb_register_driver+0x7a/0x130
[14701.502809]  ? 0xffffffffc13fa000
[14701.502838]  rtw_drv_entry+0xc0/0x1000 [8821cu]
[14701.502841]  do_one_initcall+0x46/0x1c3
[14701.502845]  ? _cond_resched+0x15/0x30
[14701.502847]  ? kmem_cache_alloc_trace+0x140/0x1c0
[14701.502850]  do_init_module+0x5a/0x220
[14701.502852]  load_module+0x14b4/0x17e0
[14701.502855]  ? __do_sys_finit_module+0xa8/0x110
[14701.502856]  __do_sys_finit_module+0xa8/0x110
[14701.502858]  do_syscall_64+0x5b/0x1a0
[14701.502860]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[14701.502861] RIP: 0033:0x7f6f4bc0c78d
[14701.502863] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d cb 56 2c 00 f7 d8 64 89 01 48
[14701.502863] RSP: 002b:00007ffd96e30e88 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[14701.502864] RAX: ffffffffffffffda RBX: 00005566b88a8c50 RCX: 00007f6f4bc0c78d
[14701.502865] RDX: 0000000000000000 RSI: 00005566b88a9240 RDI: 0000000000000004
[14701.502865] RBP: 00005566b88a9240 R08: 0000000000000000 R09: 0000000000000000
[14701.502866] R10: 0000000000000004 R11: 0000000000000246 R12: 0000000000000000
[14701.502866] R13: 00005566b88a8b30 R14: 0000000000040000 R15: 0000000000000000
[14701.502868] ---[ end trace ab0e10acefdcbe0f ]---
[14701.502966] RTW: WARN free_recv_skb_queue not empty, 8
[14701.503016] usbcore: registered new interface driver rtl8821cu
[14701.503027] RTW: module init ret=0
```

**Comment by brektrou** [comment]
Fixed for version 5.8.1
https://github.com/brektrou/rtl8821CU/commit/878da0557a66be55177559f415198c22ec85bc56
https://github.com/brektrou/rtl8821CU/commit/03a238a62a525c9ddf3bb3c0bbe7031be93122b0

**Comment by luckylittle** [comment]
@brektrou It is unfortunately still not working on Kernel `4.18.0-240.1.1.el8_3.x86_64, x86_64`. I can however confirm, that it works without any errors on `5.9.14-1.el8.elrepo.x86_64, x86_64`, RHEL v8.3.

**Comment by edrozenberg** [comment]
I see similar-looking `dmesg` output on my MiSTER FPGA system running `Linux mst1 4.19.0-socfpga-r1 #9 SMP Tue Sep 8 22:13:28 CST 2020 armv7l GNU/Linux`

Built with `make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- KSRC=../Linux-Kernel_MiSTer modules`

And I made the following changes to the `Makefile`:
```
...
CONFIG_MP_VHT_HW_TX_MODE = n
...
EXTRA_CFLAGS += -mfloat-abi=soft
```

My `dmesg` output:
```
[Fri Jan  1 19:50:02 2021] RTW: HW EFUSE
[Fri Jan  1 19:50:02 2021] RTW: 0x000: 29 81 00 BC  09 00 21 00  6E 04 A4 10  10 00 30 0B  
[Fri Jan  1 19:50:02 2021] RTW: 0x010: FF FF FF FF  FF FF FF FF  FF FF FF 02  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x020: FF FF 23 23  23 23 28 28  28 28 28 28  28 28 28 28  
[Fri Jan  1 19:50:02 2021] RTW: 0x030: 02 FF FF FF  FF FF EC FF  FF FF 2B 2B  2B 2B 2B 2B  
[Fri Jan  1 19:50:02 2021] RTW: 0x040: 30 30 30 30  30 33 FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x050: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x060: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x070: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x080: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x090: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x0A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x0B0: FF FF FF FF  FF FF FF FF  7F 06 20 00  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x0C0: FF 01 00 41  00 00 00 00  00 FF 22 FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x0D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x0E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x0F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x100: DA 0B 11 C8  E3 46 02 1C  BF CE E4 20  F4 09 03 52  
[Fri Jan  1 19:50:02 2021] RTW: 0x110: 65 61 6C 74  65 6B 0E 03  38 30 32 2E  31 31 61 63  
[Fri Jan  1 19:50:02 2021] RTW: 0x120: 20 4E 49 43  08 03 31 32  33 34 35 36  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x130: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x140: FF FF FF FF  00 00 31 0F  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x150: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x160: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x170: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x180: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x190: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x1A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x1B0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x1C0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x1D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x1E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: 0x1F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[Fri Jan  1 19:50:02 2021] RTW: hal_com_config_channel_plan chplan:0x7F
[Fri Jan  1 19:50:02 2021] RTW: [HALMAC][ALWAYS]shall R reg twice!!
[Fri Jan  1 19:50:02 2021] RTW: WARN [HALMAC][WARN]H2C/C2H ver is compatible!!
[Fri Jan  1 19:50:03 2021] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[Fri Jan  1 19:50:03 2021] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[Fri Jan  1 19:50:03 2021] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[Fri Jan  1 19:50:03 2021] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[Fri Jan  1 19:50:03 2021] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[Fri Jan  1 19:50:03 2021] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[Fri Jan  1 19:50:03 2021] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[Fri Jan  1 19:50:03 2021] RTW: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
[Fri Jan  1 19:50:03 2021] RTW: rtw_ndev_init(wlan0) if1 mac_addr=1c:bf:ce:e4:20:f4
[Fri Jan  1 19:50:03 2021] usbcore: registered new interface driver rtl8821cu
[Fri Jan  1 19:50:03 2021] RTW: module init ret=0
[Fri Jan  1 19:50:03 2021] EXT4-fs (loop0): recovery complete
[Fri Jan  1 19:50:03 2021] EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)
[Fri Jan  1 19:50:04 2021] Micrel KSZ9031 Gigabit PHY stmmac-0:01: attached PHY driver [Micrel KSZ9031 Gigabit PHY] (mii_bus:phy_addr=stmmac-0:01, irq=POLL)
[Fri Jan  1 19:50:04 2021] socfpga-dwmac ff702000.ethernet eth0: No Safety Features support found
[Fri Jan  1 19:50:04 2021] socfpga-dwmac ff702000.ethernet eth0: IEEE 1588-2008 Advanced Timestamp supported
[Fri Jan  1 19:50:04 2021] socfpga-dwmac ff702000.ethernet eth0: registered PTP clock
[Fri Jan  1 19:50:04 2021] RTW: [HALMAC][ALWAYS]shall R reg twice!!
[Fri Jan  1 19:50:04 2021] RTW: WARN [HALMAC][WARN]H2C/C2H ver is compatible!!
...
...
[Fri Jan  1 19:50:09 2021] RTW: mac_id : 0
[Fri Jan  1 19:50:09 2021] RTW: wireless_mode : 0x44
[Fri Jan  1 19:50:09 2021] RTW: mimo_type : 0
[Fri Jan  1 19:50:09 2021] RTW: bw_mode : 80MHz, ra_bw_mode : 80MHz
[Fri Jan  1 19:50:09 2021] RTW: rate_id : 10
[Fri Jan  1 19:50:09 2021] RTW: rssi : -1 (%), rssi_level : 0
[Fri Jan  1 19:50:09 2021] RTW: is_support_sgi : Y, is_vht_enable : Y
[Fri Jan  1 19:50:09 2021] RTW: disable_ra : N, disable_pt : N
[Fri Jan  1 19:50:09 2021] RTW: is_noisy : N
[Fri Jan  1 19:50:09 2021] RTW: txrx_state : 0
[Fri Jan  1 19:50:09 2021] RTW: curr_tx_rate : CCK_1M (L)
[Fri Jan  1 19:50:09 2021] RTW: curr_tx_bw : 20MHz
[Fri Jan  1 19:50:09 2021] RTW: curr_retry_ratio : 0
[Fri Jan  1 19:50:09 2021] RTW: ra_mask : 0x00000000003ffff0

[Fri Jan  1 19:50:09 2021] RTW: recv eapol packet
[Fri Jan  1 19:50:09 2021] RTW: send eapol packet
[Fri Jan  1 19:50:09 2021] RTW: recv eapol packet
[Fri Jan  1 19:50:09 2021] RTW: send eapol packet
```
